# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3380/wqimc
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
# Server settings (ServerProperties)
server:
  port: 80
  address: 0.0.0.0
  session.timeout: 45
  contextPath: /

  # Tomcat specifics
  tomcat:
    accesslog.enabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs
    
mybatis:
  config-location:  classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml 
